on:
  push:
    branches: main

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "release"

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: any::knitr
            any::rmarkdown
            any::dplyr
            any::gt
            any::purrr
            any::readxl
            any::stringr
            any::stringi
            any::tidyr
            any::ggplot2
            any::ggridges
            any::ggbeeswarm
            any::gtsummary
            any::here

            any::rnaturalearth
            ropensci/rnaturalearthhires
            any::tibble
            any::viridis
            any::scales
            any::flextable
            any::shinylive
            any::httpuv
            any::munsell
            any::colorspace
            any::labeling
            any::brms
            any::tidybayes
            any::officer
            any::broom
            any::broom.helpers

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html

      - name: Commit and Push to Main
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Render Quarto book to docs/ [skip ci]"
          branch: main
          file_pattern: docs/
